import Link from 'next/link';
import { getStore } from '@/lib/store';
import { initials } from '@/lib/utils';

export default async function Home(){const s=await getStore(); const members=[...s.members].filter(m=>m.active!==false && !m.hiddenFromPublic).sort((a,b)=>b.levelNumber-a.levelNumber||b.xp-a.xp).slice(0,3); return <main className="page">
<section className="hero"><div className="container heroGrid"><div><span className="eyebrow">🌱 Growth → Proof → Capability → Opportunity</span><h1>فقط نگو <span>رشد می‌کنی.</span><br/>رشدت رو نشون بده.</h1><p>GrowLand یک اکوسیستم رشد فردی، مهارتی و شغلی است؛ جایی که یادگیری به عمل، خروجی، شواهد و در نهایت آمادگی برای کار تبدیل می‌شود.</p><div className="heroBtns"><Link className="btn primary" href="/signup">شروع مسیر رشد</Link><Link className="btn" href="/ranking">مشاهده رکینگ</Link></div><div className="stats"><div className="stat"><strong>{s.members.length}</strong><span>عضو</span></div><div className="stat"><strong>XP</strong><span>معیار فعالیت واقعی</span></div><div className="stat"><strong>Job Ready</strong><span>هدف نهایی مسیر</span></div></div></div><div className="heroLogo"><div className="logoCard"><img src="/logo.jpg" alt="GrowLand logo"/></div></div></div></section>
<section id="about" className="section"><div className="container"><div className="sectionHead"><div><h2>GrowLand چیست؟</h2><p>آموزش فقط یکی از اجزاست؛ هویت اصلی، تبدیل رشد به توانمندی قابل اثبات است.</p></div></div><div className="glass" style={{padding:28,lineHeight:2}}>یاد بگیر → انجام بده → خروجی بساز → بازخورد بگیر → رشدت را ثابت کن → ارزیابی شو → آماده کار شو → درآمد ایجاد کن.</div></div></section>
<section className="section"><div className="container"><div className="sectionHead"><div><h2>حوزه‌های رشد</h2><p>یک مسیر را انتخاب کن و با خروجی واقعی جلو برو.</p></div></div><div className="domains">{[['🎨','طراحی'],['💻','برنامه‌نویسی'],['📱','تولید محتوا'],['🤝','فروش و مذاکره'],['🧠','مهارت‌های فردی'],['📊','کسب‌وکار'],['✍️','نویسندگی'],['🌱','زبان و رشد']].map(([i,t])=><div className="domain glass" key={t}><div className="icon">{i}</div><h3>{t}</h3><p>تمرین، فعالیت و خروجی قابل مشاهده برای ساختن شایستگی واقعی.</p></div>)}</div></div></section>
<section className="section"><div className="container"><div className="sectionHead"><div><h2>Top Members</h2><p>اعضایی که بیشترین سطح و XP ثبت‌شده را دارند.</p></div><Link className="btn" href="/members">همه ممبرها</Link></div><div className="membersGrid">{members.length?members.map(m=><div className="memberCard glass" key={m.id}><div className="memberTop"><div className="avatar">{initials(m.fullName)}</div><div><h3>{m.fullName}</h3><span className="muted">Level {m.levelNumber} · {m.xp} XP</span></div></div><div className="memberMeta">{m.skills.slice(0,3).map(x=><span className="chip" key={x.id}>{x.name}</span>)}</div></div>):<div className="empty">هنوز عضوی ثبت نشده است.</div>}</div></div></section>
<section className="section"><div className="container"><div className="sectionHead"><div><h2>اطلاعیه‌ها</h2><p>خبرها و چالش‌های جدید GrowLand</p></div></div><div className="noticeGrid">{s.announcements.map(a=><article className="notice glass" key={a.id}><span className="muted small">{new Date(a.createdAt).toLocaleDateString('fa-IR')}</span><h3>{a.title}</h3><p>{a.body}</p></article>)}</div></div></section>
<section className="section"><div className="container"><div className="ranking glass"><div className="sectionHead"><div><h2>Ranking</h2><p>رتبه‌بندی بر اساس Level و XP.</p></div><Link className="btn primary" href="/ranking">مشاهده کامل</Link></div>{members.map((m,i)=><div className="rankRow" key={m.id}><div className="rankNo">#{i+1}</div><div><b>{m.fullName}</b><div className="muted small">{m.focus}</div></div><div>Lv {m.levelNumber}</div><div className="rankXp">{m.xp} XP</div></div>)}{!members.length&&<div className="empty">هنوز داده‌ای برای رتبه‌بندی وجود ندارد.</div>}</div></div></section>
<footer className="footer"><div className="container">GrowLand — Grow Together, Go Further 🌱</div></footer></main>}
